strona/kolejki/urls.py
from django.conf.urls import url
from kolejki import views

app_name = 'kolejki'

urlpatterns = [
    # /kolejki/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /kolejki/<id>
    url(r'^(?P<pk>[0-9]+)/$', views.QueueDetails.as_view(), name="details"),
    # /kolejki/add
    url(r'^add/$', views.QueueCreate.as_view(), name='queue-add'),
    # /kolejki/<id>/update
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.QueueUpdate.as_view(), name='updateView'),
    # /kolejki/<id>/delete
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.QueueDelete.as_view(), name='DeleteView'),
    # /kolejki/matches
    url(r'^matches/$', views.MatchIndex.as_view(), name='MatchIndex'),
    # /kolejki/matches/<id>
    url(r'^matches/(?P<pk>[0-9]+)/$',
        views.MatchDetails.as_view(), name="matchdetails"),
    # /kolejki/matches/<id>/data
    url(r'^matches/(?P<pk>[0-9]+)/data/$',
        views.UpdatePlayerStatistics().DataMatchUpdate, name="match-data-update"),
    # /kolejki/matches/add
    url(r'^matches/add/$', views.MatchCreate.as_view(), name='match-add'),
    # /kolejki/matches/<id>/delete
    url(r'^matches/(?P<pk>[0-9]+)/update/$',
        views.MatchUpdate.as_view(), name='matchupdate'),
    # /kolejki/<id>/delete
    url(r'^matches/(?P<pk>[0-9]+)/delete/$',
        views.MatchDelete.as_view(), name='matchdelete'),
    # /kolejki/generate
    url(r'^generate/$', views.QueueGenerate, name="queue-generate")
]

strona/strona/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^', include('stronaGlowna.urls')),
    url(r'^statistic/', include('statistic.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^teams/', include('teams.urls')),
    url(r'^kolejki/', include('kolejki.urls')),
]

strona/teams/urls.py
from django.conf.urls import url
from . import views

app_name = "teams"

urlpatterns = [
    #/teams/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/teams/1/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #/teams/add/
    url(r'^add/$', views.CreateTeam.as_view(), name='team-add'),
    #/teams/1/update/
    url(r'^(?P<pk>[0-9]+)/$', views.UpdateTeam.as_view(), name='team-update'),
    #/teams/1/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.DeleteTeam.as_view(), name='team-delete'),
    #/teams/player/add/
    url(r'^player/add/$', views.CreatePlayer.as_view(), name='player-add'),
    #/teams/player/1/update/
    url(r'^player/(?P<pk>[0-9]+)/update/$',
        views.UpdatePlayer.as_view(), name='player-update'),
    #/teams/player/1/delete/
    url(r'^player/(?P<pk>[0-9]+)/delete/$',
        views.DeletePlayer.as_view(), name='player-delete'),

]

strona/kolejki/models.py
from django.db import models
from teams.models import Team
from django.core.urlresolvers import reverse

# Create your models here.


class Queue(models.Model):
    startDate = models.DateField()
    finishDate = models.DateField()

    def get_absolute_url(self):
        return reverse('kolejki:details', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.startDate) + " -  " + str(self.finishDate)


class Match(models.Model):
    queue = models.ForeignKey(Queue)
    matchDate = models.DateTimeField()

    home = models.ForeignKey(Team, related_name='gospodarz')
    away = models.ForeignKey(Team, related_name='gosc')

    awayGoals = models.IntegerField(default=0)
    homeGoals = models.IntegerField(default=0)

    commentary = models.TextField(max_length=500, default="")
    # def create(cls,queue,matchDate,home,away):
    #     match = cls(queue=queue,matchDate=matchDate,home=home,away=away)
    #     return match
    # def __init__(self,queue,matchDate,home,away):
    #     super(Match, self).__init__()
    #     self.queue = queue
    #     self.matchDate = matchDate
    #     self.home = home
    #     self.away = away

    def __str__(self):
        return str(self.home) + " - " + str(self.away)

    def get_absolute_url(self):
        return reverse('kolejki:matchdetails', kwargs={'pk': self.pk})

strona/teams/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Team(models.Model):
    name = models.TextField(max_length=50)
    matches = models.IntegerField(default=0)
    win = models.IntegerField(default=0)
    draw = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    goals = models.IntegerField(default=0)
    points = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('teams:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Player(models.Model):
    name = models.TextField(max_length=50)
    surname = models.TextField(max_length=50)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    goals = models.IntegerField(default=0)
    yellow_cards = models.IntegerField(default=0)
    red_cards = models.IntegerField(default=0)
    second_yellow_cards = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('teams:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.team.name + " - " + self.name + " " + self.surname + " "

strona/kolejki/forms.py
from django import forms
from .models import Match, Queue
from teams.models import Team, Player


class GoalForm(forms.Form):
    homeGoals = forms.IntegerField(label='Home Goals:', min_value=0, initial=0)
    awayGoals = forms.IntegerField(label='Away Goals:', min_value=0, initial=0)

    def __init__(self, *args, **kwargs):
        extra = kwargs.pop('extra')
        super(GoalForm, self).__init__(*args, **kwargs)
        for i, fields in enumerate(extra):
            self.fields['goal_%s' % i] = forms.IntegerField(
                label=str(fields) + " Goals:", min_value=0, initial=0)
            self.fields['yellow_%s' % i] = forms.IntegerField(
                label="Yellow cards", min_value=0, max_value=2, initial=0)
            self.fields['red_%s' % i] = forms.IntegerField(
                label="Red cards", min_value=0, max_value=1, initial=0)

    def extra_g(self):
        for name, value in self.cleaned_data.items():
            if name.startswith('goal_'):
                yield (name, value)

    def extra_y(self):
        for name, value in self.cleaned_data.items():
            if name.startswith('yellow_'):
                yield (name, value)

    def extra_r(self):
        for name, value in self.cleaned_data.items():
            if name.startswith('red_'):
                yield (name, value)

strona/kolejki/views.py
from django.views import generic
from kolejki.models import Queue, Match
from django.urls import reverse_lazy
from .models import Match
from teams.models import Team, Player
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from .forms import GoalForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from statistic.models import StatisticsPlayer
from itertools import chain
from stronaGlowna import views
from random import randint
from django.utils import timezone
from django.views import View
from statistic.views import UpdateTeamStatistics
from teams.views import updateStatistics
from datetime import datetime
from datetime import timedelta
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'kolejki/index.html'
    context_object_name = 'allQueues'

    def get_queryset(self):
        return Queue.objects.all()


class QueueDetails(generic.DetailView):
    model = Queue
    template_name = "kolejki/details.html"
    def get_queryset(self):
        return Queue.objects.all()
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return render(request, self.template_name, {
                'queue': context,
                'currentDate': datetime.now(),
            })


class QueueCreate(generic.CreateView):
    model = Queue
    fields = ['startDate', 'finishDate']


class QueueUpdate(generic.UpdateView):
    model = Queue
    fields = ['startDate', 'finishDate']


class QueueDelete(generic.DeleteView):
    model = Queue
    fields = ['startDate', 'finishDate']
    success_url = reverse_lazy('kolejki:index')


class MatchIndex(generic.ListView):
    template_name = 'kolejki/matchIndex.html'
    context_object_name = 'allMatches'

    def get_queryset(self):
        return Match.objects.all()


class MatchDetails(generic.DetailView):
    model = Match
    template_name = "kolejki/matchdetails.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return render(request, self.template_name, {
                'match': context,
                'playerStatistics': StatisticsPlayer.objects.all(),
            })


class MatchCreate(generic.CreateView):
    model = Match
    fields = ['home', 'away', 'queue', 'matchDate', 'commentary']


class MatchUpdate(generic.UpdateView):
    model = Match
    fields = ['home', 'away', 'queue', 'matchDate', 'commentary']


def QueueGenerate(request):
    if request.method == 'GET':
        return render(request, 'kolejki/queue-generate.html')
    else:
        Queue.objects.all().delete()
        teams = Team.objects.all()
        #teams = [1,2,3,4,5,6,7,8]
        matches = []
        date = datetime.now()
        #date = datetime.strptime("2017-05-05", "%Y-%m-%d")
        for round in create_schedule(list(teams)):
            queue = Queue()
            queue.startDate = date
            delay = timedelta(days=7)
            finish = date + delay
            queue.finishDate = finish
            queue.save()
            for team in round:
                day_delay = timedelta(days=2)
                hours = timedelta(hours=18)
                matchday = date + randint(0, 3) * day_delay + hours
                home = team[0]
                away = team[1]
                match = Match()
                match.queue = queue
                match.matchDate = matchday
                match.home = home
                match.away = away
                match.save()
            date = date + delay
        return redirect('kolejki:index')
       # return redirect('kolejki:index')


class MatchDelete(generic.DeleteView):
    model = Match
    fields = ['home', 'away', 'queue', 'matchDate', 'commentary']
    success_url = reverse_lazy('kolejki:index')


class UpdatePlayerStatistics():
    hgoals = 0
    agoals = 0

    def save_answer(self, request, match, player_list, stats):
        #print ((stats[0][0] ) )
        p = player_list[int(stats[0][0][5::1])]
        if(StatisticsPlayer.objects.filter(name=p.name, surname=p.surname, team_id=p.team.pk, match_id=match.pk).exists()):
            sp = StatisticsPlayer.objects.get(
                name=p.name, surname=p.surname, team_id=p.team.pk, match_id=match.pk)
        else:
            sp = StatisticsPlayer(
                name=p.name, surname=p.surname, team_id=p.team.pk, match_id=match.pk)
        sp.goals = stats[0][1]
        sp.yellow_cards = stats[1][1]
        sp.red_cards = stats[2][1]
        sp.save()

    def check_answer(self, request, match, player_list, stats):
        #print ((stats[0][0] ) )
        p = player_list[int(stats[0][0][5::1])]
        if(StatisticsPlayer.objects.filter(name=p.name, surname=p.surname, team_id=p.team.pk, match_id=match.pk).exists()):
            sp = StatisticsPlayer.objects.get(
                name=p.name, surname=p.surname, team_id=p.team.pk, match_id=match.pk)
        else:
            sp = StatisticsPlayer(
                name=p.name, surname=p.surname, team_id=p.team.pk, match_id=match.pk)

        if(match.home.pk == sp.team_id):
            self.hgoals += int(stats[0][1])
        else:
            self.agoals += int(stats[0][1])

    def DataMatchUpdate(self, request, pk):
        # if this is a POST request we need to process the form data
        match = get_object_or_404(Match, pk=pk)
        try:
            h = match.home.player_set.all()
            a = match.away.player_set.all()
        except (KeyError, Player.DoesNotExist):
            return render(request, 'kolejki/data.html', {
                'match': match,
                'error_message': "Player does not exist"
            })
        player_list = list(chain(h, a))
        form = GoalForm(request.POST or None, extra=player_list)
        self.hgoals = 0
        self.agoals = 0
        if form.is_valid():
            match.homeGoals = form.cleaned_data['homeGoals']
            match.awayGoals = form.cleaned_data['awayGoals']
        # for item in request.POST.keys():
            #print(  item + ' - ' + request.POST[item])
            for (goal, value1) in form.extra_g():
                for (yellow, value2) in form.extra_y():
                    for (red, value3) in form.extra_r():
                        stats = ((goal, value1),
                                 (yellow, value2), (red, value3))
                        self.check_answer(request, match, player_list, stats)
                        break
                    break 
            if(self.hgoals == match.homeGoals and self.agoals == match.awayGoals):
                for (goal, value1) in form.extra_g():
                    for (yellow, value2) in form.extra_y():
                        for (red, value3) in form.extra_r():
                            stats = ((goal, value1),
                                     (yellow, value2), (red, value3))
                            self.save_answer(
                                request, match, player_list, stats)
                            break
                        break
                match.save()
            else:

                return render(request, 'kolejki/data.html', {
                    'match': match,
                    'error_message': "Nieprawidłowe dane"
                })
            # create a form instance and populate it with data from the request:
            # check whether it's valid:

            # check whether it's valid:

                # process the data in form.cleaned_data as required
                # ...
                # redirect to a new URL:
            
            UpdateTeamStatistics()
            updateStatistics()
            return redirect('statistic:match-player-stats')
        # if a GET (or any other method) we'll create a blank form

        return render(request, 'kolejki/data.html', {'form': form, 'match': match})


def create_schedule(list):
    """ Create a schedule for the teams in the list and return it"""
    s = []

    #if len(list) % 2 == 1: list = list + ["BYE"]

    for i in range(len(list) - 1):

        mid = len(list) / 2
        l1 = list[:int(mid)]
        l2 = list[int(mid):]
        l2.reverse()

        # Switch sides after each round
        if(i % 2 == 1):
            s = s + [zip(l1, l2)]
        else:
            s = s + [zip(l2, l1)]

        list.insert(1, list.pop())

    return s

strona/kolejki/templates/kolejki/data.html
{% extends 'base.html'%} {% block content %} {% if error_message %}

{% extends 'validateUser.html'%} {% block content %} {% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    <div class="container">
        <div class="row">
            <div class="panel-body">
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token%} {% include 'kolejki/form_template.html'%}
                    <div class="form-group">
                        <button type="submit" class="btn btn-submit">Submit </button>
                    </div>
                </form>
            </div>
        </div>
    </div>>
    {%endblock%}

strona/kolejki/templates/kolejki/details.html
{% extends 'base.html'%} {% block content %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kolejki/style.css' %}" /> {% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    <div class="row">
        <div class="col-xs-12">
            <h3> Kolejka</h3>
            {% if queue.queue.match_set.all.exists %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Dzień</th>
                        <th></th>
                        <th>Gospodarz</th>
                        <th>wynik</th>
                        <th>Gość</th>
                        <th></th>

                    </tr>
                </thead>
                {%for match in queue.queue.match_set.all %}
                <tr>
                    <td>
                        {{match.matchDate.day}}.{{match.matchDate.month}} {{match.matchDate.time.hour}}:00
                    </td>
                    </td>
                    <td>
                        <img class="logo" src="{% static 'kolejki/' %}{{ match.home.id}}.jpg" alt="">
                    </td>
                    <td>
                        <a href="{% url 'kolejki:matchdetails' match.id %} "> {{match.home}}</a>
                    </td>
                    <td>xd</td>
                    <td>
                        {% if currentDate <= match.matchDate %} 
                        <a href="{% url 'kolejki:matchdetails' match.id %} "> - : - </a>
                            {% else %}
                            <a href="{% url 'kolejki:matchdetails' match.id %} ">  {{match.homeGoals}} : {{match.awayGoals}} </a>                        
                                {% endif %}

                    </td>
                    <td>
                        <a href="{% url 'kolejki:matchdetails' match.id %} ">   {{match.away}} </a>
                    </td>
                    <td>
                        <img class="logo" src="{% static "kolejki/" %}{{ match.away.id}}.jpg" alt="">
                    </td>
                    {% if not user.is_authenticated %} 
    {% else %} 
        {% for group in user.groups.all %} 
            {% if group.name == 'Organizer' or group.name == 'Admin' %} 
                <td>
                        <form action="{% url 'kolejki:match-data-update' match.id %}">
                            <button type="submit" class="btn btn-submit button btn-sm">Szczegóły</button>
                        </form>
                        <form action="{% url 'kolejki:matchdetails' match.id %}update">
                            <button type="submit" class="btn btn-submit button btn-sm"> Edytuj</button>
                        </form>
                        <form action="{% url 'kolejki:matchdetails' match.id %}delete">
                            <button type="submit" class="btn btn-danger button btn-sm from-button"> Usun</button>
                        </form>
                    </td>
            {% else %}
            {% endif %} 
        {% endfor %} 
    {% endif %}
                   

                </tr>
                {%endfor%}
            </table>
            {% else %}
            <h3> Nie istnieje żaden mecz</h3>
            {% endif %}
        </div>
    </div>
    <a href="/kolejki/">Powrót</a>
    </form>
    {% endblock %}

strona/kolejki/templates/kolejki/form_template.html
{% for field in form %} {% csrf_token %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.error}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">
        {{field}}
    </div>
</div>
{% endfor %}

strona/kolejki/templates/kolejki/index.html
{% extends 'base.html'%} {% block content %}
    <h1>Terminarz</h1>
    {% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    {% if allQueues%}
    <div class="table">
        <ul class="list-group">
            {% for queue in allQueues %}
            <li class="list-group-item"><a href="{% url 'kolejki:details' queue.id %}"> Kolejka rozpoczynająca się w {{queue.startDate}}</a></li>
            {% endfor %}
        </ul>
        <br/> {% else%}
        <h3> Nie istnieje żadna kolejka</h3>
        {% endif%}
    </div>
    <h2>Generuj kolejki</h2>
    <a href=" {%  url 'kolejki:queue-generate' %} ">Generuj</a>
    <br/>
    <a href="/">Powrót</a>
{% endblock %}

strona/kolejki/templates/kolejki/matchIndex.html
{% extends 'base.html'%} {% block content %} 
<div class="container">
    {% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    <h1> Wszystkie mecze </h1>
    <ul class="list-group col-md-6">
        {% for match in allMatches %}
        <li class="list-group-item"> <a href=" {%  url 'kolejki:matchdetails' match.id  %} "> {{ match }} </a></li>
        {% endfor %}
    </ul>
    <a href="/">Powrót do strony głównej</a> {% endblock %}

strona/kolejki/templates/kolejki/match_confirm_delete.html
{% extends 'validateUser.html'%} {% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{%endblock%}

strona/kolejki/templates/kolejki/match_form.html
{% extends 'validateUser.html'%} {% block content %}
<div class="container">
    <div class="row">
        <div class="panel-body">
            <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token%} {% include 'kolejki/form_template.html'%}
                <div class="form-group">
                    <button type="submit" class="btn btn-submit">Submit </button>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

strona/kolejki/templates/kolejki/matchdetails.html
{% extends 'base.html'%} {% block content %}
{% if error_message %}
    <p><strong>{{error_message}}</p></strong> {% endif %}
        <h2 class="page-header">Mecz {{match.match.home }} {{match.match.homeGoals}} vs {{match.match.awayGoals}} {{match.match.away}}</h2>
<div class="row">
    <div class="col-md-6">
<table class="table table-striped">
                <thead>
                    <th>Piłkarz</th>
                    <th>Bramki</th>
                    <th>Żółte kartki</th>
                    <th>Czerwone kartki</th>
                </thead>
                <h3>{{match.match.home.name}}</h1>
                    {% for p in match.match.home.player_set.all %} {% for ps in playerStatistics %} 
                    {% if p.name == ps.name and p.surname == ps.surname and p.team.pk == ps.team_id %}
                    <tbody>
                        <td>{{ps.name}} {{ps.surname}}</td>
                        <td>{{ps.goals}}</td>
                        <td>{{ps.yellow_cards}}</td>
                        <td>{{ps.red_cards}}</td>
                    </tbody>
                    {% else %} {% endif %} {% endfor %} {% endfor %}
                    </table>
    </div>
        <div class="col-md-6">
        
            <table class="table table-striped">
                <thead>
                    <th>Piłkarz</th>
                    <th>Bramki</th>
                    <th>Żółte kartki</th>
                    <th>Czerwone kartki</th>
                </thead>
                <h3>{{match.match.away.name}}</h1>
                    {% for p in match.match.away.player_set.all %} {% for ps in playerStatistics %} 
                    {% if p.name == ps.name and p.surname == ps.surname and p.team.pk == ps.team_id %}

                    <td>{{ps.name}} {{ps.surname}}</td>
                    <td>{{ps.goals}}</td>
                    <td>{{ps.yellow_cards}}</td>
                    <td>{{ps.red_cards}}</td>
                    </tbody>
                    {% else %} 
                    {% endif %} 
                    {% endfor %}
                     {% endfor %}
                     </table>
    </div>
  
</div>
          
<a href="/kolejki/matches">Powrót</a> {% endblock %}

strona/kolejki/templates/kolejki/queue-generate.html
 {% extends 'validateUser.html'%} {% block content %}  
<h2 class="page-header">Generowanie kolejek</h2>
{% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
<form action="" method="POST">
    {% csrf_token%}
    <input type="submit" value="Generuj" />
</form>
{% endblock %}

strona/kolejki/templates/kolejki/queue_confirm_delete.html
{% extends 'validateUser.html'%} {% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
<a href="kolejki/{{object.id}}">Powrót</a>dddd {% endblock %}

strona/kolejki/templates/kolejki/queue_form.html
{% extends 'validateUser.html'%} {% block content %}
<div class="container">
    <div class="row">
        <div class="panel-body">
            <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token%} {% include 'kolejki/form_template.html'%}
                <div class="form-group">
                    <button type="submit" class="btn btn-submit">Submit </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}