strona/strona/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^', include('stronaGlowna.urls')),
    url(r'^statistic/', include('statistic.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^teams/', include('teams.urls')),
    url(r'^kolejki/', include('kolejki.urls')),
]

strona/teams/urls.py
from django.conf.urls import url
from . import views

app_name = "teams"

urlpatterns = [
    #/teams/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/teams/1/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #/teams/add/
    url(r'^add/$', views.CreateTeam.as_view(), name='team-add'),
    #/teams/1/update/
    url(r'^(?P<pk>[0-9]+)/$', views.UpdateTeam.as_view(), name='team-update'),
    #/teams/1/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.DeleteTeam.as_view(), name='team-delete'),
    #/teams/player/add/
    url(r'^player/add/$', views.CreatePlayer.as_view(), name='player-add'),
    #/teams/player/1/update/
    url(r'^player/(?P<pk>[0-9]+)/update/$',
        views.UpdatePlayer.as_view(), name='player-update'),
    #/teams/player/1/delete/
    url(r'^player/(?P<pk>[0-9]+)/delete/$',
        views.DeletePlayer.as_view(), name='player-delete'),

]

strona/teams/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Team(models.Model):
    name = models.TextField(max_length=50)
    matches = models.IntegerField(default=0)
    win = models.IntegerField(default=0)
    draw = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    goals = models.IntegerField(default=0)
    points = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('teams:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Player(models.Model):
    name = models.TextField(max_length=50)
    surname = models.TextField(max_length=50)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    goals = models.IntegerField(default=0)
    yellow_cards = models.IntegerField(default=0)
    red_cards = models.IntegerField(default=0)
    second_yellow_cards = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('teams:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.team.name + " - " + self.name + " " + self.surname + " "

strona/teams/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Team, Player
from statistic.models import StatisticsPlayer
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'teams/index.html'
    context_object_name = 'all_teams'

    def get_queryset(self):
        return Team.objects.all()


class DetailView(generic.DetailView):
    model = Player
    template_name = 'teams/detail.html'

    def get_queryset(self):
        return Team.objects.all()


class CreateTeam(CreateView):
    model = Team
    fields = ['name']


class UpdateTeam(UpdateView):
    model = Team
    fields = ['name']


class DeleteTeam(DeleteView):
    model = Team
    success_url = reverse_lazy('teams:index')


class CreatePlayer(CreateView):
    model = Player
    fields = ['name', 'surname', 'team']
    success_url = reverse_lazy('teams:index')

class UpdatePlayer(UpdateView):
    model = Player
    fields = ['name', 'surname', 'team']


class DeletePlayer(DeleteView):
    model = Player
    success_url = reverse_lazy('teams:index')


def updateStatistics(): 
            plist=Player.objects.all()
            pslist=StatisticsPlayer.objects.all()
            for p in plist : 
                p.goals = 0
                p.yellow_cards = 0
                p.red_cards =0
                p.second_yellow_cards = 0
                for ps in pslist:
                    if p.name==ps.name and p.surname ==ps.surname and p.team.id==ps.team_id :
                        p.goals=p.goals+ps.goals
                        p.yellow_cards=p.yellow_cards+ps.yellow_cards
                        p.red_cards=p.red_cards+ps.red_cards
                        p.second_yellow_cards=p.second_yellow_cards+ps.second_yellow_cards
                p.save()
            return 

strona/teams/templates/teams/add.html
{% extends 'validateUser.html'%} {% block content %}
<h1>Dodawanie Druzyn</h1>
{% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    <form action="{% url 'teams:add' %}" method="POST">
        {% csrf_token %} Name:
        <br>
        <input type="text" name="name">
        <input type="submit" value="Submit">
    </form>
{%endblock%}

strona/teams/templates/teams/detail.html
 {% extends 'base.html'%} {% block content %}
<div class="container">
    {% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    <h1>{{team.name}}</h1>
    <ul class="list-group">
        {% for player in team.player_set.all %}
        <li class="list-group-item">{{player.name}} {{player.surname}}
             {% if not user.is_authenticated %}
    {% else %} 
        {% for group in user.groups.all %} 
            {% if group.name == 'Organizer' or group.name == 'Admin' %} 
                 <div class="btn-group">
                <form action="{% url 'teams:player-update' player.id %}" method="POST">
                    {% csrf_token%}
                    <button type="submit" class="btn btn-submit button btn-sm from-button"> Edytuj</button>
                    <button type="submit" formaction="{% url 'teams:player-delete' player.id %}" class="btn btn-danger button btn-sm from-button"> Usun</button>
                </form>
            </div>
            {% else %}
           
            {% endif %} 
        {% endfor %} 
    {% endif %}
           
        </li>
        {% endfor %}
    </ul>
        {% if not user.is_authenticated %}
    {% else %} 
        {% for group in user.groups.all %} 
            {% if group.name == 'Organizer' or group.name == 'Admin' %} 
                 <div class="btn-group">
                <form action="{% url 'teams:player-add' %}" method="POST">
                    {% csrf_token%}
                    <button type="submit" class="btn btn-submit button btn-sm from-button"> Dodaj</button>
                </form>
                <form action="{% url 'teams:team-delete' team.pk %}" method="POST">
                    {% csrf_token%}
                    <button type="submit" class="btn btn-danger button btn-sm from-button"> Usun</button>
                </form>
            </div>
            {% else %}
           
            {% endif %} 
        {% endfor %} 
    {% endif %}
    <a href="/teams">Powrót</a> {% endblock %}
</div>

strona/teams/templates/teams/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.error}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">
        {{field}}
    </div>
</div>
{% endfor %}

strona/teams/templates/teams/index.html
 {% extends 'base.html'%} {% block content %}
<div class="container">
    {% if error_message %}
<p><strong>{{error_message}}</p></strong> {% endif %}
    {%if all_teams %}
    <h3>Team list:</h3>
    <div class="col-md-6">
        <ul class="list-group">
            {%for team in all_teams%}
            <li class="list-group-item">
                <a href="{% url 'teams:detail' team.id %}">{{team.name}}</a>
            </li>
            {% endfor %}
        </ul>
          {% if not user.is_authenticated %}
    {% else %} 
        {% for group in user.groups.all %} 
            {% if group.name == 'Organizer' or group.name == 'Admin' %} 
                 <div class="btn-group">
                <form action="{% url 'teams:team-add' %}" method="POST">
                    {% csrf_token%}
                    <button type="submit" class="btn btn-submit button btn-sm from-button"> Dodaj</button>
                </form>
            </div>
            {% else %}
           
            {% endif %} 
        {% endfor %} 
    {% endif %}
        <a href="/">Powrót</a>
    </div>
    {%else%}
    <h3>No teams in database</h3>
    {%endif%}
     {% endblock %}
</div>

strona/teams/templates/teams/player_confirm_delete.html
 {% extends 'validateUser.html'%} {% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{%endblock%}

strona/teams/templates/teams/player_form.html
 {% extends 'validateUser.html'%} {% block content %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %} {% include "teams/form-template.html" %}
    <div class='form-group'>
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
{%endblock%}

strona/teams/templates/teams/team_form.html
 {% extends 'validateUser.html'%} {% block content %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %} {% include "teams/form-template.html" %}
    <div class='form-group'>
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
{%endblock%}