strona/kolejki/urls.py
from django.conf.urls import url
from kolejki import views

app_name = 'kolejki'

urlpatterns = [
    # /kolejki/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /kolejki/<id>
    url(r'^(?P<pk>[0-9]+)/$', views.QueueDetails.as_view(), name="details"),
    # /kolejki/add
    url(r'^add/$', views.QueueCreate.as_view(), name='queue-add'),
    # /kolejki/<id>/update
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.QueueUpdate.as_view(), name='updateView'),
    # /kolejki/<id>/delete
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.QueueDelete.as_view(), name='DeleteView'),
    # /kolejki/matches
    url(r'^matches/$', views.MatchIndex.as_view(), name='MatchIndex'),
    # /kolejki/matches/<id>
    url(r'^matches/(?P<pk>[0-9]+)/$',
        views.MatchDetails.as_view(), name="matchdetails"),
    # /kolejki/matches/<id>/data
    url(r'^matches/(?P<pk>[0-9]+)/data/$',
        views.UpdatePlayerStatistics().DataMatchUpdate, name="match-data-update"),
    # /kolejki/matches/add
    url(r'^matches/add/$', views.MatchCreate.as_view(), name='match-add'),
    # /kolejki/matches/<id>/delete
    url(r'^matches/(?P<pk>[0-9]+)/update/$',
        views.MatchUpdate.as_view(), name='matchupdate'),
    # /kolejki/<id>/delete
    url(r'^matches/(?P<pk>[0-9]+)/delete/$',
        views.MatchDelete.as_view(), name='matchdelete'),
    # /kolejki/generate
    url(r'^generate/$', views.QueueGenerate, name="queue-generate")
]

strona/strona/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^', include('stronaGlowna.urls')),
    url(r'^statistic/', include('statistic.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^teams/', include('teams.urls')),
    url(r'^kolejki/', include('kolejki.urls')),
]

strona/stronaGlowna/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'stronaGlowna'

urlpatterns = [
    # /
    url(r'^$', views.Index, name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout,
        {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^register/$', views.UserFormView.as_view(), name='register')
]

strona/teams/urls.py
from django.conf.urls import url
from . import views

app_name = "teams"

urlpatterns = [
    #/teams/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/teams/1/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #/teams/add/
    url(r'^add/$', views.CreateTeam.as_view(), name='team-add'),
    #/teams/1/update/
    url(r'^(?P<pk>[0-9]+)/$', views.UpdateTeam.as_view(), name='team-update'),
    #/teams/1/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.DeleteTeam.as_view(), name='team-delete'),
    #/teams/player/add/
    url(r'^player/add/$', views.CreatePlayer.as_view(), name='player-add'),
    #/teams/player/1/update/
    url(r'^player/(?P<pk>[0-9]+)/update/$',
        views.UpdatePlayer.as_view(), name='player-update'),
    #/teams/player/1/delete/
    url(r'^player/(?P<pk>[0-9]+)/delete/$',
        views.DeletePlayer.as_view(), name='player-delete'),

]

strona/stronaGlowna/models.py
from django.db import models

# Create your models here.

strona/stronaGlowna/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

strona/stronaGlowna/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model, views
from django.views import View
from django import forms
from django.views.generic import View, TemplateView
from .forms import UserForm
from kolejki.models import Queue
from django.contrib.auth.models import Group
from datetime import datetime


def Index(request):
    template_name = "stronaGlowna/index.html"
    currDate = datetime.now().date()
    queue = Queue.objects.all()
    que=Queue() 

    for q in queue:
        if(q.startDate <= currDate and q.finishDate >= currDate):
            que = q.match_set.order_by('matchDate') 
            break 
    return render(request,template_name,{'queue': que, 'currentDate':datetime.now()})

   


class UserFormView(View):
    form_class = UserForm
    template_name = 'stronaGlowna/registration_form.html'

    # new account
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process registration
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            confirmation = form.cleaned_data.get("confirm_password")
            if confirmation == password:
                user.set_password(password)
                if(not Group.objects.filter(name='User').exists()):
                    g = Group(name='User')
                    g.save()
                g = Group.objects.get(name='User')
                user.save()
                g.user_set.add(user)
                user = authenticate(username=username, password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('stronaGlowna:index')
            else:
                raise forms.ValidationError("Passwords don't match")
                # return render_to_response("registration_form.html", {'invalid': True })
        return render(request, self.template_name, {'form': form})

strona/stronaGlowna/templates/stronaGlowna/form_template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.error}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">
        {{field}}
    </div>
</div>
{% endfor %}

strona/stronaGlowna/templates/stronaGlowna/index.html
{% extends 'base.html'%} 
{% block content %}

{{currentDate}}
 <h2>Aktualna kolejka</h2>
 {% load static %}
 {% if queue.exists %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Dzień</th>
                        <th></th>
                        <th>Gospodarz</th>
                        <th>wynik</th>
                        <th>Gość</th>
                        <th></th>
                    </tr>
                </thead> 
                {%for match in queue %}
                <tr class="match-row">
                    <td class="match-day">
                        {{match.matchDate.day}}.{{match.matchDate.month}} {{match.matchDate.time.hour}}:00
                    </td>
                    </td>
                    <td>
                         <img  class="logo"src="{% static "kolejki/" %}{{ match.home.id}}.jpg" alt="">
                    </td>
                    <td>
                        <a href="{% url 'kolejki:matchdetails' match.id %} "> {{match.home}}</a>
                    </td>
                    <td>
                        {% if currentDate <= match.matchDate %}

                        <a href="{% url 'kolejki:matchdetails' match.id %} ">  - : - </a>
                        {% else %}
                        <a href="{% url 'kolejki:matchdetails' match.id %} ">  {{match.homeGoals}} : {{match.awayGoals}} </a>
                        {% endif %}
                        
                    </td>
                    <td>
                        <a href="{% url 'kolejki:matchdetails' match.id %} ">   {{match.away}} </a>
                    </td>
                     <td>
                         <img  class="logo"src="{% static "kolejki/" %}{{ match.away.id}}.jpg" alt="">
                    </td>
                </tr>
                {%endfor%}
            </table>
            {% else %}
              <h3> Nie istnieje żaden mecz</h3>
            {% endif %}

   
 {% endblock %}

strona/stronaGlowna/templates/stronaGlowna/registration_form.html
{% extends 'base.html'%} {% block content %}
{% if user.is_authenticated  %}
    <h3>Jesteś już zalogowany</h3>
{% else %}
    <div class="container">
        <h1>Rejestracja</h1>
    </div>
    <form class="form-horizontal" role="form" action="" method="POST">
        {% csrf_token %} {% include 'stronaGlowna/form_template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Zatwierdź</button>
            </div>
        </div>
    </form>
{%endif%}
{% endblock %}